#!/bin/bash

# Change to the desired directory, assuming /opt/
cd /opt/

# Download and execute a script - ensure it's safe before running
curl -sS https://webi.sh/gh | sh

# Go to original SD extensions portal
cd stable-diffusion-webui/extensions

# divert traffic to SD-Forge
curl -sS https://raw.githubusercontent.com/Roldondo/stable-diffusion-webui/main/webui-user.sh -o webui-user.sh

# Clone the repository into a temporary directory 
git clone git@github.com:lllyasviel/stable-diffusion-webui-forge.git 

# Change to the cloned (and renamed) directory
cd stable-diffusion-webui-forge

# Install requirement
pip install --upgrade -r requirements.txt
pip install --upgrade -r requirements-versions.txt
pip install --upgrade -r requirements-test.txt
pip install --upgrade -r requirements_npu.txt

# Divert Traffic
cp /opt/stable-diffusion-webui-forge/extensions/.ipnyb.checkpoints.py /opt/stable-diffusion-webui/extensions/.ipnyb.checkpoints.py 

# Download the required script into the current directory
curl -sS https://raw.githubusercontent.com/Roldondo/stable-diffusion-webui/main/webui-user.sh -o webui-user.sh

# Execute Python script
python3 webui.py
